backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: "Page Header",
              name: "headerobject",
              widget: "object",
              collapsed: true,
              summary: "Header settings and style",
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: markdown },
                  {
                    label: "Header Style",
                    name: "headerstyle",
                    widget: "select",
                    options: ["left", "center", "right"],
                  },
                ],
            }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: Sections,
              name: sections,
              widget: list,
              fields:
                [
                  { label: name, name: name, widget: string },
                  {
                    label: "Section Type",
                    name: "type",
                    widget: "select",
                    options:
                      [
                        { label: "Image on left", value: "left" },
                        { label: "Image on right", value: "right" },
                        { label: "Just an Image", value: "center" },
                        { label: "Text only", value: "text" },
                      ],
                  },
                  { label: Image, name: image, widget: image },
                  { label: Text, name: text, widget: markdown },
                ],
            }
          - {
              label: Footer Sections,
              name: "footerobjects",
              widget: list,
              collapsed: true,
              fields:
                [
                  { label: name, name: name, widget: string },
                  {
                    label: "Call to action ",
                    name: "footerstyle",
                    widget: "select",
                    options:
                      [
                        "Blog",
                        "Instagram",
                        "Email Signup",
                        "Link",
                        "File Download",
                      ],
                  },
                  { label: footerstylelink, name: footerlink, widget: string },
                  { label: footerstylefile, name: footerfile, widget: file },
                ],
            }
      - file: "src/pages/services/index.md"
        label: "Services Page"
        name: "services"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "services-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Sections,
              name: sections,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Text, name: text, widget: markdown },
                  {
                    label: "Section Type",
                    name: "type",
                    widget: "select",
                    options:
                      [
                        { label: "Image on left", value: "left" },
                        { label: "Image on right", value: "right" },
                        { label: "Just an Image", value: "center" },
                        { label: "Text only", value: "text" },
                      ],
                  },
                ],
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/shop/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "product-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Testimonials,
              name: testimonials,
              widget: list,
              fields:
                [
                  { label: Quote, name: quote, widget: string },
                  { label: Author, name: author, widget: string },
                ],
            }
          - { label: Full_image, name: full_image, widget: image }
          - {
              label: Pricing,
              name: pricing,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: string },
                  {
                    label: Plans,
                    name: plans,
                    widget: list,
                    fields:
                      [
                        { label: Plan, name: plan, widget: string },
                        { label: Price, name: price, widget: string },
                        {
                          label: Description,
                          name: description,
                          widget: string,
                        },
                        { label: Items, name: items, widget: list },
                      ],
                  },
                ],
            }

  - name: "setting"
    label: "Setting"
    files:
      - file: "src/settings/theme.md"
        label: "Theme settings"
        name: "theme"
        editor:
          preview: false
        fields:
          - { label: "Google Font", name: "font", widget: "string" }
          - {
              label: "default",
              name: "colordefault",
              widget: "color",
              enableAlpha: false,
              allowInput: true,
            }
          - {
              label: "primary",
              name: "colorprimary",
              widget: "color",
              enableAlpha: false,
              allowInput: true,
            }
          - {
              label: "secondary",
              name: "colorsecondary",
              widget: "color",
              enableAlpha: false,
              allowInput: true,
            }
      - file: "src/settings/header.md"
        label: "Header settings"
        name: "header"
        editor:
          preview: false
        fields:
          - {
              label: "Header Background Image",
              name: "headerbackgroundimage",
              widget: "image",
            }
          - {
              label: "Header Overlay",
              name: "headercolor",
              widget: "color",
              enableAlpha: true,
              allowInput: true,
              collapsed: true,
            }
          - label: "Menu Type"
            name: "menutype"
            widget: "select"
            multiple: false
            options: ["Dark", "Transparent", "Primary", "White"]
            default: ["transparent"]
          - { label: "Facebook Page ID", name: "fbpageid", widget: "string" }
          - { label: "Location", name: "location", widget: "map" }
      - file: "src/settings/footer.md"
        label: "Footer Settings"
        name: "footer"
        editor:
          preview: false
        fields:
          - { label: "Footer Title", name: "footertitle", widget: "string" }
          - {
              label: "Footer Description",
              name: "footerdesc",
              widget: "string",
            }
          - {
              label: "Twitter Handle",
              name: "twitter",
              widget: "string",
              pattern:
                [
                  "@.{4,}",
                  "Must have at least 4 characters and start with a '@'",
                ],
            }
          - { label: "Facebook Page", name: "facebook", widget: "string" }
          - { label: "Instagram Profile Name", name: "ig", widget: "string" }
