backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: "Page Header",
              name: "headerobject",
              widget: "object",
              collapsed: true,
              summary: "SEO Page Information",
              fields:
                [
                  { label: SEO Title, name: title, widget: string },
                  { label: SEO Description, name: description, widget: string },
                ],
            }
          - {
              label: "Page Title",
              name: "pagetitle",
              widget: "string",
              required: false,
            }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - {
              label: Sections,
              name: sections,
              widget: list,
              fields:
                [
                  {
                    label: "Section Type",
                    name: "type",
                    widget: "select",
                    options:
                      [
                        {
                          label: "Image on left - Text on right",
                          value: "Image on left - Text on right",
                        },
                        {
                          label: "Image on right - Text on left",
                          value: "Image on right - Text on left",
                        },
                        { label: "Image only", value: "Image only" },
                        { label: "Text only", value: "Text only" },
                      ],
                  },
                  { label: Image, name: image, widget: image, required: false },
                  {
                    label: Text,
                    name: text,
                    widget: markdown,
                    required: false,
                  },
                ],
            }
          - {
              label: Footer Sections,
              name: "footerobjects",
              widget: list,
              collapsed: true,
              fields:
                [
                  {
                    label: "Call to action ",
                    name: "footerstyle",
                    widget: "select",
                    options: ["Blog", "Instagram", "Discovery", "Email"],
                  },
                ],
            }
      - file: "src/pages/about/index.md"
        label: "About Me"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - {
              label: "Page Header",
              name: "headerobject",
              widget: "object",
              collapsed: true,
              summary: "SEO Page Information",
              fields:
                [
                  { label: SEO Title, name: title, widget: string },
                  { label: SEO Description, name: description, widget: string },
                ],
            }
          - {
              label: "Page Title",
              name: "pagetitle",
              widget: "string",
              required: false,
            }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - {
              label: Sections,
              name: sections,
              widget: list,
              fields:
                [
                  {
                    label: "Section Type",
                    name: "type",
                    widget: "select",
                    options:
                      [
                        {
                          label: "Image on left - Text on right",
                          value: "Image on left - Text on right",
                        },
                        {
                          label: "Image on right - Text on left",
                          value: "Image on right - Text on left",
                        },
                        { label: "Image only", value: "Image only" },
                        { label: "Text only", value: "Text only" },
                      ],
                  },
                  { label: Image, name: image, widget: image, required: false },
                  {
                    label: Text,
                    name: text,
                    widget: markdown,
                    required: false,
                  },
                ],
            }
          - {
              label: Footer Sections,
              name: "footerobjects",
              widget: list,
              collapsed: true,
              fields:
                [
                  {
                    label: "Call to action ",
                    name: "footerstyle",
                    widget: "select",
                    options: ["Blog", "Instagram", "Discovery", "Email"],
                  },
                ],
            }
      - file: "src/pages/thrive/index.md"
        label: "Thrive Coaching"
        name: "thrive"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "thrive-page",
            }
          - {
              label: "Page Header",
              name: "headerobject",
              widget: "object",
              collapsed: true,
              summary: "SEO Page Information",
              fields:
                [
                  { label: SEO Title, name: title, widget: string },
                  { label: SEO Description, name: description, widget: string },
                ],
            }
          - {
              label: "Page Title",
              name: "pagetitle",
              widget: "string",
              required: false,
            }
          - {
              label: "Body",
              name: "body",
              widget: "markdown",
              default: true,
              required: false,
            }
          - {
              label: Sections,
              name: sections,
              widget: list,
              fields:
                [
                  {
                    label: "Section Type",
                    name: "type",
                    widget: "select",
                    options:
                      [
                        {
                          label: "Image on left - Text on right",
                          value: "Image on left - Text on right",
                        },
                        {
                          label: "Image on right - Text on left",
                          value: "Image on right - Text on left",
                        },
                        { label: "Image only", value: "Image only" },
                        { label: "Text only", value: "Text only" },
                      ],
                  },
                  { label: Image, name: image, widget: image, required: false },
                  {
                    label: Text,
                    name: text,
                    widget: markdown,
                    required: false,
                  },
                ],
            }
          - {
              label: Footer Sections,
              name: "footerobjects",
              widget: list,
              collapsed: true,
              fields:
                [
                  {
                    label: "Call to action ",
                    name: "footerstyle",
                    widget: "select",
                    options: ["Blog", "Instagram", "Discovery", "Email"],
                  },
                ],
            }
      - file: "src/pages/inclusivity/index.md"
        label: "Inclusivity"
        name: "inclusivity"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "inclusivity-page",
            }
          - {
              label: "Page Header",
              name: "headerobject",
              widget: "object",
              collapsed: true,
              summary: "SEO Page Information",
              fields:
                [
                  { label: SEO Title, name: title, widget: string },
                  { label: SEO Description, name: description, widget: string },
                ],
            }
          - {
              label: "Page Title",
              name: "pagetitle",
              widget: "string",
              required: false,
            }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - {
              label: Sections,
              name: sections,
              widget: list,
              fields:
                [
                  {
                    label: "Section Type",
                    name: "type",
                    widget: "select",
                    options:
                      [
                        {
                          label: "Image on left - Text on right",
                          value: "Image on left - Text on right",
                        },
                        {
                          label: "Image on right - Text on left",
                          value: "Image on right - Text on left",
                        },
                        { label: "Image only", value: "Image only" },
                        { label: "Text only", value: "Text only" },
                      ],
                  },
                  { label: Image, name: image, widget: image, required: false },
                  {
                    label: Text,
                    name: text,
                    widget: markdown,
                    required: false,
                  },
                ],
            }
          - {
              label: Footer Sections,
              name: "footerobjects",
              widget: list,
              collapsed: true,
              fields:
                [
                  {
                    label: "Call to action ",
                    name: "footerstyle",
                    widget: "select",
                    options: ["Blog", "Instagram", "Discovery", "Email"],
                  },
                ],
            }
      - file: "src/pages/events/index.md"
        label: "Yoga Events"
        name: "events"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "events-page",
            }
          - {
              label: "Page Header",
              name: "headerobject",
              widget: "object",
              collapsed: true,
              summary: "SEO Page Information",
              fields:
                [
                  { label: SEO Title, name: title, widget: string },
                  { label: SEO Description, name: description, widget: string },
                ],
            }
          - {
              label: "Page Title",
              name: "pagetitle",
              widget: "string",
              required: false,
            }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - {
              label: Sections,
              name: sections,
              widget: list,
              fields:
                [
                  {
                    label: "Section Type",
                    name: "type",
                    widget: "select",
                    options:
                      [
                        {
                          label: "Image on left - Text on right",
                          value: "Image on left - Text on right",
                        },
                        {
                          label: "Image on right - Text on left",
                          value: "Image on right - Text on left",
                        },
                        { label: "Image only", value: "Image only" },
                        { label: "Text only", value: "Text only" },
                      ],
                  },
                  { label: Image, name: image, widget: image, required: false },
                  {
                    label: Text,
                    name: text,
                    widget: markdown,
                    required: false,
                  },
                ],
            }
          - {
              label: Footer Sections,
              name: "footerobjects",
              widget: list,
              collapsed: true,
              fields:
                [
                  {
                    label: "Call to action ",
                    name: "footerstyle",
                    widget: "select",
                    options: ["Blog", "Instagram", "Discovery", "Email"],
                  },
                ],
            }
      - file: "src/pages/privacy/index.md"
        label: "Privacy Policy"
        name: "privacy"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "privacy-page",
            }
          - {
              label: "Page Header",
              name: "headerobject",
              widget: "object",
              collapsed: true,
              summary: "SEO Page Information",
              fields:
                [
                  { label: SEO Title, name: title, widget: string },
                  { label: SEO Description, name: description, widget: string },
                ],
            }
          - {
              label: "Page Title",
              name: "pagetitle",
              widget: "string",
              required: false,
            }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - {
              label: Sections,
              name: sections,
              widget: list,
              fields:
                [
                  {
                    label: "Section Type",
                    name: "type",
                    widget: "select",
                    options:
                      [
                        {
                          label: "Image on left - Text on right",
                          value: "Image on left - Text on right",
                        },
                        {
                          label: "Image on right - Text on left",
                          value: "Image on right - Text on left",
                        },
                        { label: "Image only", value: "Image only" },
                        { label: "Text only", value: "Text only" },
                      ],
                  },
                  { label: Image, name: image, widget: image, required: false },
                  {
                    label: Text,
                    name: text,
                    widget: markdown,
                    required: false,
                  },
                ],
            }
          - {
              label: Footer Sections,
              name: "footerobjects",
              widget: list,
              collapsed: true,
              fields:
                [
                  {
                    label: "Call to action ",
                    name: "footerstyle",
                    widget: "select",
                    options: ["Blog", "Instagram", "Discovery", "Email"],
                  },
                ],
            }

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "setting"
    label: "Setting"
    files:
      - file: "src/settings/theme.md"
        label: "Theme settings"
        name: "theme"
        editor:
          preview: false
        fields:
          - { label: "Google Header Font", name: "fontalt", widget: "string" }
          - { label: "Google Text Font", name: "font", widget: "string" }
          - {
              label: "Email you would like the contact us pages form to be sent to.",
              name: "contactemail",
              widget: "string",
            }
          - {
              label: "default",
              name: "colordefault",
              widget: "color",
              enableAlpha: false,
              allowInput: true,
            }
          - {
              label: "primary",
              name: "colorprimary",
              widget: "color",
              enableAlpha: false,
              allowInput: true,
            }
          - {
              label: "secondary",
              name: "colorsecondary",
              widget: "color",
              enableAlpha: false,
              allowInput: true,
            }
      - file: "src/settings/header.md"
        label: "Header settings"
        name: "header"
        editor:
          preview: false
        fields:
          - {
              label: "Header Background Image",
              name: "headerbackgroundimage",
              widget: "image",
            }
          - {
              label: "Header Overlay",
              name: "headercolor",
              widget: "color",
              enableAlpha: true,
              allowInput: true,
              collapsed: true,
            }
          - label: "Menu Type"
            name: "menutype"
            widget: "select"
            multiple: false
            options: ["Dark", "Transparent", "Primary", "White"]
            default: ["transparent"]
          - { label: "Facebook Page ID", name: "fbpageid", widget: "string" }
          - { label: "Location", name: "location", widget: "map" }
      - file: "src/settings/footer.md"
        label: "Footer Settings"
        name: "footer"
        editor:
          preview: false
        fields:
          - { label: "Footer Title", name: "footertitle", widget: "string" }
          - {
              label: "Footer Description",
              name: "footerdesc",
              widget: "string",
            }
          - {
              label: "Twitter Handle",
              name: "twitter",
              widget: "string",
              pattern:
                [
                  "@.{4,}",
                  "Must have at least 4 characters and start with a '@'",
                ],
            }
          - { label: "Facebook Page", name: "facebook", widget: "string" }
          - { label: "Instagram Profile Name", name: "ig", widget: "string" }
